spring:
  data:
      mongodb:
          username: mongo
          password: mongo
#          host: localhost
          host: ms_mongodb
          port: 27017
          database: customer
          authentication-database: admin
server:
    port: 8090


