spring:
    data:
          mongodb:
              username: mongo
              password: mongo
              host: ms_mongodb
              port: 27017
              database: customer
              authentication-database: admin
    kafka:
          consumer:
              bootstrap-servers: ms_kafka:9092
              group-id: paymentGroup, orderGroup
              auto-offset-reset: earliest
              key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
              value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
              properties:
                  spring.json.trusted.packages: '*'
                  spring.json.type.mapping: orderConfirmation:com.ppa.ecomm.records.OrderConfirmation,paymentConfirmation:com.ppa.ecomm.records.PaymentConfirmation
    mail:
        host: ms_maildev
        port: 1025
        username: rutvi
        password: rutvi
        properties:
            mail:
                smtp:
                    trust: "*"
                auth: true
                starttls:
                    enabled: true
                connectionTimeOut: 5000
                timeout: 3000
                writetimeout: 5000
server:
    ports: 8040
