spring:
    datasource:
        url: jdbc:postgresql://ms_pgsql:5432/order
        username: postgres
        password: postgres
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: update
        database: postgresql
        database-platform: org.hibernate.dialect.PostgreSQLDialect
    kafka:
        producer:
            bootstrap-servers: ms_kafka:9092
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
            properties:
                spring.json.type.mapping: orderConfirmation:com.ppa.ecomm.records.kafka.OrderConfirmation
server:
    port: 8070

application:
    config:
        customer-url: http://gateway-service:8222/api/v1/customers
        product-url: http://gateway-service:8222/api/v1/products
        payment-url: http://gateway-service:8222/api/v1/payments