spring:
    datasource:
        url: jdbc:postgresql://ms_pgsql:5432/product
        username: postgres
        password: postgres
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: validate
        database: postgresql
        database-platform: org.hibernate.dialect.PostgreSQLDialect
    flyway:
        baseline-on-migrate: true
        enabled: true
        baseline-description: init
        baseline-version: 0
        url: jdbc:postgresql://ms_pgsql:5432/product
        user: postgres
        password: postgres
server:
    port: 8050